#!/bin/bash
set -o pipefail
# gen-cron.sh (run with -V for version; see git log for full changelog)
# ------------------------------------------------------------------------------
# Description: generates a crontab block for snapsend.sh/delsnaps.sh from a
# host-local config file, instead of hand-editing scattered cron lines.
#
# Usage: gen-cron.sh [-c CONFIG] [--install] [-V]
# Options:
#   -c <FILE>   Config file to read (default: jobs.<hostname -s>.conf next to this script)
#   --install   Install the generated block into this user's crontab (idempotent:
#               replaces the existing managed block instead of appending). Without
#               this flag, the block is only printed to stdout for review.
#   -V          Print version and exit
#
# Config file is plain bash, sourced by this script. It declares jobs via two
# functions:
#
#   add_job    tier=<label> schedule="<5-field cron>" src="<dataset[,dataset...]>" \
#              dst="<path or [user@]host:dataset>" [prefix="<snapshot name prefix>"] \
#              [flags="<snapsend.sh flags>"] notify="<notify-fail.sh description>"
#
#   add_retain tier=<label> schedule="<5-field cron>" prune_root="<pool/path>" \
#              pattern="<snapshot name substring to match>" \
#              retain="<delsnaps.sh -h/-d/-w/-m/-y (age) or -H/-D/-W/-M/-Y (count) flags>" \
#              notify="<notify-fail.sh description>"
#
# add_retain is deliberately separate from add_job: pruning in production runs
# once per (prune_root, tier) over the whole target recursively, not once per
# source dataset -- see design_cron_config_generator memory for the reasoning.
#
# flags="-f" (force full send) and flags="-n" (dry-run) are rejected at generate
# time: -f in a standing cron job means destroy-and-reseed the target every run,
# -n never actually sends anything -- neither makes sense as a recurring job.
#
# All add_retain patterns sharing the same prune_root are validated against
# each other at generate time: since delsnaps.sh matches by literal string
# prefix, a pattern that is a prefix of (or equal to) another tier's pattern
# for the same prune_root would let one tier's snapshots leak into another
# tier's retention run. This is rejected regardless of retain mode -- it is
# always a configuration mistake, not a valid use case.
###############################################################################
#BEGIN 1 [GLOBAL CONFIGURATION]
###############################################################################
VERSION='v1.1'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$SCRIPT_DIR"
NOTIFY_SCRIPT="${NOTIFY_SCRIPT:-/root/scripts/notify-fail.sh}"
CRON_LOG="${CRON_LOG:-/root/scripts/cron.log}"
LOCKFILE="${GEN_CRON_LOCKFILE:-/var/run/gen-cron.install.lock}"
MARKER_BEGIN="# BEGIN zfs-backup-managed (generated by gen-cron.sh -- do not hand-edit, re-run gen-cron.sh instead)"
MARKER_END="# END zfs-backup-managed"

declare -a JOB_LINES=()
declare -a RETAIN_LINES=()
declare -A SEEN_RETAIN=()

# Parallel arrays (index-aligned) recording every add_retain declaration's
# prune_root/pattern/tier, for the cross-tier overlap check in
# validate_retain_patterns (see BEGIN 3.5).
declare -a RETAIN_ROOTS=()
declare -a RETAIN_PATTERNS=()
declare -a RETAIN_TIERS=()
###############################################################################
#END 1

###############################################################################
#BEGIN 2 [HELPERS]
###############################################################################
die() { echo "gen-cron.sh: error: $*" >&2; exit 1; }

usage() {
    grep '^#' "${BASH_SOURCE[0]}" | sed -n '2,26p' | sed 's/^# \{0,1\}//'
}

# Rejects flags that never make sense in a standing/recurring cron job.
lint_flags() {
    local flags="$1" ctx="$2" tok
    for tok in $flags; do
        case "$tok" in
            -f) die "$ctx: flag -f (force full send) not allowed in a recurring job -- it would destroy and re-seed the target every run" ;;
            -n) die "$ctx: flag -n (dry-run) not allowed in a recurring job -- it never actually sends anything" ;;
        esac
    done
}

# Parses "key=value" args into the caller's local vars via nameref-free case match.
# Usage: _parse_kv <error-context> "$@" then read the matching case in caller.
###############################################################################
#END 2

###############################################################################
#BEGIN 3 [CONFIG DSL: add_job / add_retain]
###############################################################################
add_job() {
    local tier="" schedule="" src="" dst="" prefix="" flags="" notify=""
    local kv key value
    for kv in "$@"; do
        key="${kv%%=*}"; value="${kv#*=}"
        case "$key" in
            tier) tier="$value" ;;
            schedule) schedule="$value" ;;
            src) src="$value" ;;
            dst) dst="$value" ;;
            prefix) prefix="$value" ;;
            flags) flags="$value" ;;
            notify) notify="$value" ;;
            *) die "add_job: unknown field '$key'" ;;
        esac
    done

    [ -n "$tier" ]     || die "add_job: 'tier' is required"
    [ -n "$schedule" ] || die "add_job: 'schedule' is required (tier=$tier)"
    [ -n "$src" ]      || die "add_job: 'src' is required (tier=$tier)"
    [ -n "$dst" ]      || die "add_job: 'dst' is required (tier=$tier)"
    [ -n "$notify" ]   || die "add_job: 'notify' is required (tier=$tier, src=$src)"

    lint_flags "$flags" "add_job tier=$tier notify=\"$notify\""

    local cmd="$REPO_DIR/snapsend.sh"
    [ -n "$prefix" ] && cmd="$cmd -m \"$prefix\""
    [ -n "$flags" ]  && cmd="$cmd $flags"
    cmd="$cmd \"$src\" \"$dst\""

    JOB_LINES+=("$schedule $cmd 2>>$CRON_LOG || $NOTIFY_SCRIPT \"$notify\"")
}

add_retain() {
    local tier="" schedule="" prune_root="" pattern="" retain="" notify=""
    local kv key value
    for kv in "$@"; do
        key="${kv%%=*}"; value="${kv#*=}"
        case "$key" in
            tier) tier="$value" ;;
            schedule) schedule="$value" ;;
            prune_root) prune_root="$value" ;;
            pattern) pattern="$value" ;;
            retain) retain="$value" ;;
            notify) notify="$value" ;;
            *) die "add_retain: unknown field '$key'" ;;
        esac
    done

    [ -n "$tier" ]       || die "add_retain: 'tier' is required"
    [ -n "$schedule" ]   || die "add_retain: 'schedule' is required (tier=$tier)"
    [ -n "$prune_root" ] || die "add_retain: 'prune_root' is required (tier=$tier)"
    [ -n "$pattern" ]    || die "add_retain: 'pattern' is required (tier=$tier, prune_root=$prune_root)"
    [ -n "$retain" ]     || die "add_retain: 'retain' is required (tier=$tier, prune_root=$prune_root)"
    [ -n "$notify" ]     || die "add_retain: 'notify' is required (tier=$tier, prune_root=$prune_root)"

    local dedup_key="${prune_root}|${tier}"
    [ -z "${SEEN_RETAIN[$dedup_key]:-}" ] || die "add_retain: duplicate declaration for prune_root='$prune_root' tier='$tier' -- one add_retain per (prune_root,tier)"
    SEEN_RETAIN[$dedup_key]=1

    RETAIN_ROOTS+=("$prune_root")
    RETAIN_PATTERNS+=("$pattern")
    RETAIN_TIERS+=("$tier")

    RETAIN_LINES+=("$schedule $REPO_DIR/delsnaps.sh -R \"$prune_root\" \"$pattern\" $retain 2>>$CRON_LOG || $NOTIFY_SCRIPT \"$notify\"")
}

# delsnaps.sh matches snapshots by literal string prefix ("$snapname" == "$pat"*).
# If two add_retain declarations share a prune_root and one pattern is a prefix
# of (or equal to) the other, a single snapshot can match both tiers' prune
# runs. In age mode this is a latent correctness bug; in count mode it is
# actively destructive (the finer-grained tier's snapshots -- always the most
# recent -- eat the coarser tier's keep budget on the very first run). Catch
# it here, once, across every tier for a given prune_root, rather than relying
# on each cron job to independently guess it's scoped correctly.
validate_retain_patterns() {
    local n="${#RETAIN_ROOTS[@]}"
    local i j pi pj
    for ((i = 0; i < n; i++)); do
        for ((j = i + 1; j < n; j++)); do
            [ "${RETAIN_ROOTS[$i]}" = "${RETAIN_ROOTS[$j]}" ] || continue
            pi="${RETAIN_PATTERNS[$i]}"
            pj="${RETAIN_PATTERNS[$j]}"
            if [[ "$pi" == "$pj"* ]] || [[ "$pj" == "$pi"* ]]; then
                die "add_retain: pattern overlap for prune_root='${RETAIN_ROOTS[$i]}' -- tier='${RETAIN_TIERS[$i]}' pattern='$pi' and tier='${RETAIN_TIERS[$j]}' pattern='$pj': one pattern is a prefix of (or equal to) the other, so a single snapshot could match both retention rules. Use mutually exclusive prefixes (e.g. 'automated_daily_' / 'automated_weekly_', not 'automated_' / 'automated_daily_')."
            fi
        done
    done
}
###############################################################################
#END 3

###############################################################################
#BEGIN 4 [BLOCK GENERATION]
###############################################################################
generate_block() {
    echo "$MARKER_BEGIN"
    echo "# Source: $CONFIG -- DO NOT EDIT BY HAND, re-run gen-cron.sh instead"
    local line
    for line in "${JOB_LINES[@]}"; do echo "$line"; done
    if [ "${#JOB_LINES[@]}" -gt 0 ] && [ "${#RETAIN_LINES[@]}" -gt 0 ]; then
        echo ""
    fi
    for line in "${RETAIN_LINES[@]}"; do echo "$line"; done
    echo "$MARKER_END"
}
###############################################################################
#END 4

###############################################################################
#BEGIN 5 [IDEMPOTENT CRONTAB INSTALL]
###############################################################################
install_crontab() {
    command -v flock >/dev/null || die "flock command not found"
    command -v crontab >/dev/null || die "crontab command not found"

    exec 200>"$LOCKFILE"
    if ! flock -n 200; then
        die "another gen-cron.sh --install is already running (lock: $LOCKFILE) -- retry once it finishes"
    fi

    local current
    current="$(crontab -l 2>/dev/null)" || current=""

    local begin_count end_count
    begin_count=$(printf '%s\n' "$current" | grep -Fc "$MARKER_BEGIN")
    end_count=$(printf '%s\n' "$current" | grep -Fc "$MARKER_END")

    if [ "$begin_count" -gt 1 ] || [ "$end_count" -gt 1 ]; then
        die "malformed crontab: multiple '$MARKER_BEGIN'/'$MARKER_END' pairs found -- fix manually before retrying"
    fi
    if [ "$begin_count" -ne "$end_count" ]; then
        die "malformed crontab: found $begin_count BEGIN marker(s) but $end_count END marker(s) -- fix manually before retrying"
    fi

    local new_block
    new_block="$(generate_block)"

    local new_crontab="" line in_block=0
    if [ "$begin_count" -eq 1 ]; then
        while IFS= read -r line || [ -n "$line" ]; do
            if [ "$line" = "$MARKER_BEGIN" ]; then
                new_crontab+="$new_block"$'\n'
                in_block=1
                continue
            fi
            if [ "$line" = "$MARKER_END" ]; then
                in_block=0
                continue
            fi
            [ "$in_block" -eq 1 ] && continue
            new_crontab+="$line"$'\n'
        done <<<"$current"
    else
        if [ -n "$current" ]; then
            new_crontab="$current"$'\n\n'"$new_block"$'\n'
        else
            new_crontab="$new_block"$'\n'
        fi
    fi

    local new_crontab_norm
    new_crontab_norm="$(printf '%s' "$new_crontab")"

    if [ "$current" = "$new_crontab_norm" ]; then
        echo "gen-cron.sh: no changes -- crontab already up to date" >&2
        return 0
    fi

    printf '%s\n' "$new_crontab_norm" | crontab - || die "crontab install failed"
    echo "gen-cron.sh: crontab updated from $CONFIG" >&2
}
###############################################################################
#END 5

###############################################################################
#BEGIN 6 [MAIN]
###############################################################################
CONFIG=""
INSTALL=0

while [ $# -gt 0 ]; do
    case "$1" in
        -c) CONFIG="$2"; shift 2 ;;
        --install) INSTALL=1; shift ;;
        -V|--version) echo "$VERSION"; exit 0 ;;
        -h|--help) usage; exit 0 ;;
        *) die "unknown argument: $1 (see -h)" ;;
    esac
done

if [ -z "$CONFIG" ]; then
    CONFIG="$SCRIPT_DIR/jobs.$(hostname -s 2>/dev/null || hostname).conf"
fi
[ -f "$CONFIG" ] || die "config file not found: $CONFIG (pass -c to specify one)"

# shellcheck source=/dev/null
source "$CONFIG"

[ "${#JOB_LINES[@]}" -gt 0 ] || [ "${#RETAIN_LINES[@]}" -gt 0 ] || die "no add_job/add_retain declarations found in $CONFIG"

validate_retain_patterns

if [ "$INSTALL" -eq 1 ]; then
    install_crontab
else
    generate_block
fi
###############################################################################
#END 6
