#!/bin/bash
###############################################################################
# lib-cron.sh -- the ONE way this project writes a crontab.
#
# WHY THIS FILE EXISTS
#
# Until 2026-08-02 three programs wrote crontabs and none of them shared a line
# of code:
#
#   deploy.sh      four hand-rolled `crontab -l | ... | crontab -` sites
#                  (self-update line, capacity line, the account's auto-pull
#                  line, and a removal path), each of which REWRITES THE WHOLE
#                  crontab to add or drop one line;
#   gen-cron.sh    the `# BEGIN/END zfs-backup-managed` block;
#   zfs-backup.sh  its own backup/restore around gen-cron.sh --install.
#
# The `# BEGIN/END zfs-backup-host` block used to be listed here as
# zfs-backup.sh's. It never was, in the end: deploy.sh owns it
# (CRON_HOST_BLOCK), and zfs-backup.sh's copy of the markers existed only for
# the root-to-account migration verb, which was retired on 2026-08-19. The
# markers went with it on 2026-08-20; this line lagged both.
#
# Two of deploy.sh's lines were not inside any block at all -- loose in the
# crontab, indistinguishable from something a human put there, protected only
# by every other writer being careful to copy what it did not recognise.
#
# That design has already cost this project twice: a crontab was wiped during a
# live test (`$0` vs `BASH_SOURCE[0]`), and metropolis pve2 ran four minutes
# with no backup jobs when one writer's block came out before another's went in.
# The six assertions in zfs-backup.sh (assert_target_block_not_clobbered,
# assert_no_foreign_managed_block, assert_cron_config_matches_installed,
# crontab_of_or_die, managed_block_fingerprint, job_identity) are compensating
# controls for exactly this: they exist to keep writers from eating each other.
#
# So: ONE writer, several requesters. Each requester owns a NAMED BLOCK and can
# touch nothing else -- not because it promises not to, but because the only
# entry point takes the block name as an argument and refuses to write outside
# it.
#
# WHAT THIS FILE DOES NOT DO
#
# It does not know what a cron line means, which account should run it, or
# whether the job it names exists. That stays with the requester. This file
# answers exactly one question: how do you replace one named region of a
# crontab without losing the rest of it.
#
# Sourced by deploy.sh, gen-cron.sh and zfs-backup.sh. Deliberately NOT part of
# lib-zfs-snap.sh: that library is the send/receive/quiesce engine and is
# sourced by the transfer scripts, which never write a crontab.
#
# update-control.sh keeps its own duplicated helpers on purpose (it must survive
# a rollback of the repo it lives outside of) and does not source this file.
###############################################################################

# Marker lines. BEGIN carries a human-readable tail after the name -- the
# installed crontabs already look like this, and matching must not depend on
# that tail, or adopting an existing block would fail:
#
#   # BEGIN zfs-backup-managed (generated by gen-cron.sh -- do not hand-edit...)
#   # END zfs-backup-managed
cron_block_begin_re() { printf '^# BEGIN %s(\\b|$)' "$1"; }
cron_block_end_re()   { printf '^# END %s[[:space:]]*$' "$1"; }

# A block name is a path component of the crontab's namespace, so it gets the
# same treatment every other externally-supplied identifier in this project
# gets: validated, never interpolated on trust.
cron_block_name_valid() {   # <name>
    case "$1" in
        ""|*[!A-Za-z0-9._-]*) return 1 ;;
        *) return 0 ;;
    esac
}

# Which crontab(1) form addresses <user>: the bare one, or `-u <user>`.
#
# "root" counts as self even when the caller is not root, and that is a
# deliberate carry-over from the code this file replaces, not an oversight:
#
#   * in every real invocation the program IS root by the time it touches a
#     crontab -- installing root's own block, or the account's with -u. The two
#     rules cannot differ there;
#   * the suites run as an ordinary user and emulate root, which is what lets
#     them cover the root paths on any machine without being root. Under a
#     strict rule they would silently read an empty crontab through a stub that
#     only knows `-l`, and twelve assertions would pass for the wrong reason.
#
# The footgun this leaves -- a non-root process asking for root's crontab and
# getting its own -- is unreachable here: the only caller that names root is the
# one installing root's block, which requires being root anyway. Changing the
# semantics silently during a refactor would have been the worse choice.
cron_is_self() {   # <user>
    [ "$1" = "$(id -un)" ] || [ "$1" = root ]
}

# ---- serialization (REV-20260802-034 F2) ------------------------------------
#
# Read-back proves THIS write landed; it cannot prove nothing was lost between
# the read and the write. gen-cron.sh's own GEN_CRON_LOCKFILE is private to its
# own --install run, and deploy.sh never took it -- so a gen-cron install and a
# deploy.sh run against the same user could each read the same stale copy, and
# the second write would silently erase the first's change. Read-modify-write
# without a shared lock is the exact race the single-writer refactor exists to
# remove, and adding one writer without one just gave the race a narrower door.
#
# So every mutating entry point takes a lock keyed by the TARGET USER, held
# from before the first read to after the read-back or the restore decision. A
# requester does not have to remember a separate lock to be safe, because there
# is no path from a requester to crontab(1) that skips this one.
#
# flock(1) locks are held by an OPEN FILE DESCRIPTION, not by the process --
# opening the same lock file a second time from the same process and flock-ing
# THAT would self-deadlock rather than succeed, because flock has no concept of
# "this process already holds it". That is why every mutating function below
# has an internal *_impl that does the real work UNLOCKED, and only the
# outermost public call opens the lock: cron_block_adopt_line's wrapper calls
# cron_block_ensure_line_impl directly, never the locked cron_block_ensure_line.
# REV-20260803-035. This used to be `${CRON_LOCK_DIR:-/run}`, then fall back to
# $TMPDIR/tmp if /run was not WRITABLE -- which sounds like a reasonable
# default until two different identities write the SAME target user's
# crontab: root can create files under /run, a delegated account normally
# cannot, so root locked /run/lib-cron.<user>.lock while the account's own
# gen-cron.sh locked /tmp/lib-cron.<user>.lock. Two different lock objects
# guarding one crontab is not a lock, and it silently reopened the exact F2
# race this file exists to close -- caught because F2's own contention tests
# (section P below) pass CRON_LOCK_DIR identically to both sides of the test,
# so they could not see two real identities diverge.
#
# The fix is one fixed, persistent, deploy-managed directory and NO caller-local
# fallback of any kind: every identity that can legitimately write a managed
# crontab (root, and the delegated account deploy.sh's Phase 4/8 put in group
# zfsalert) can create files here, via the same 2775 root:zfsalert treatment
# already used for ALERT_SHARED_DIR -- see deploy.sh's Phase 4. If it is ever
# missing or unwritable, that is refused, not silently redirected elsewhere.
CRON_LOCK_DIR="${CRON_LOCK_DIR:-/var/lib/zfs-snapshot-all/locks}"
CRON_LOCK_TIMEOUT="${CRON_LOCK_TIMEOUT:-10}"
declare -gA CRON_LOCK_FD=()

cron_lock_path() { printf '%s/lib-cron.%s.lock' "$CRON_LOCK_DIR" "$1"; }   # <user>

# ---- pause markers (deploy.sh --pause/--resume) -----------------------------
# REV-20260803-036 F5: defined HERE, not in deploy.sh, because every ordinary
# writer in this file -- not just deploy.sh -- must recognise and refuse to
# silently undo a pause. A convention only deploy.sh understood was exactly
# the gap: gen-cron.sh --install, or an ensure/adopt-line call, could
# reconstruct an active block seconds after --pause reported success, because
# the shared lock only orders writes -- it does not enforce an invariant
# after the lock is released.
#
# Recognised STRUCTURALLY, never by substring search (F3's mistake): an
# unrelated comment that happens to mention the fullcron marker, or a hand
# line that merely contains the block marker text, must never be mistaken for
# the actual paused shape.
CRON_PAUSE_MARKER="# zfs-snapshot-all: PAUSED"
CRON_PAUSE_BLOCK_MARKER="# ZSA-PAUSED"
CRON_PAUSE_LINE_PREFIX="#ZSA-PAUSED#"

# Is the WHOLE crontab exactly deploy.sh --pause --fullcron's placeholder --
# one line, starting with the fullcron marker? -> 0 paused, 1 not.
cron_fullcron_paused() {   # <curfile>
    local cur="$1" n
    n=$(wc -l < "$cur" 2>/dev/null | tr -d ' ')
    [ "$n" = "1" ] || return 1
    grep -qE "^${CRON_PAUSE_MARKER}( |\$)" "$cur" 2>/dev/null
}

# Is <name>'s block, as it stands in <curfile>, in the paused shape left by
# deploy.sh --pause's default block mode (its first body line is the paused
# header)? -> 0 paused, 1 not paused or absent.
cron_block_paused() {   # <curfile> <name>
    local cur="$1" name="$2" first
    cron_block_locate "$cur" "$name" || return 1
    [ "$CRON_B" -gt 0 ] && [ "$CRON_E" -gt $((CRON_B + 1)) ] || return 1
    first=$(sed -n "$((CRON_B + 1))p" "$cur")
    case "$first" in
        "$CRON_PAUSE_BLOCK_MARKER"*) return 0 ;;
        *) return 1 ;;
    esac
}

# The F5 enforcement point: every ORDINARY (not pause-aware) writer calls this
# before rendering a change, and refuses rather than silently making a paused
# block -- or a fully-paused crontab -- active again. deploy.sh's own
# pause/resume code renders the whole new crontab itself and commits it
# through cron_replace_all_impl directly, which does NOT call this guard --
# that path is the one thing allowed to change a paused shape. Every other
# caller of cron_block_install/cron_block_ensure_line/cron_block_adopt_line
# (gen-cron.sh --install, zfs-backup.sh's host-block lines, deploy.sh's own
# updater/capacity lines) goes through it automatically, with no change
# required at the call site.
cron_paused_guard() {   # <curfile> <name>  -> 0 ok to write, 1 refused (CRON_ERR set)
    local cur="$1" name="$2"
    if cron_fullcron_paused "$cur"; then
        CRON_ERR="'$name': the crontab is currently paused as a whole (deploy.sh --pause --fullcron) -- run deploy.sh --resume before any ordinary write"
        return 1
    fi
    if cron_block_paused "$cur" "$name"; then
        CRON_ERR="'$name': this block is currently paused (deploy.sh --pause) -- run deploy.sh --resume before any ordinary write"
        return 1
    fi
    return 0
}

# Non-blocking with a bounded wait, then a clear diagnostic and NO write --
# never a silent, unbounded hang, and never a write that skipped the queue.
cron_lock_acquire() {   # <user>  -> 0 held, 1 refused (CRON_ERR set)
    local user="$1" path fd
    if [ -n "${CRON_LOCK_FD[$user]:-}" ]; then
        CRON_ERR="the crontab lock for '$user' is already held by this process -- that is a bug in the caller, not lock contention"
        return 1
    fi
    if [ ! -d "$CRON_LOCK_DIR" ] || [ ! -w "$CRON_LOCK_DIR" ]; then
        CRON_ERR="the shared lock directory $CRON_LOCK_DIR is missing or not writable by $(id -un 2>/dev/null || echo '?') -- refusing to write rather than silently choosing a different lock namespace another writer would not share. Run deploy.sh to (re)create it (2775 root:zfsalert)."
        return 1
    fi
    path=$(cron_lock_path "$user")
    # A predictable path in a directory writable by more than one identity is
    # exactly where a symlink could be pre-planted to redirect the write below
    # at whatever it points to. Refuse rather than open through one.
    if [ -L "$path" ]; then
        CRON_ERR="$path is a symlink -- refusing to lock through it"
        return 1
    fi
    # A bare `exec` with no command applies ALL of its redirections to the
    # current shell PERMANENTLY, not just to this statement -- so a trailing
    # `2>/dev/null` here doesn't scope to the exec attempt, it silently and
    # permanently nukes the whole process's stderr from this point on (found
    # by a rollback's warn/die output vanishing from a caller's captured
    # `$(... 2>&1)` even though the rollback itself ran correctly). Validate
    # writability with a real command first -- its redirect IS scoped to that
    # command alone -- then do the persistent exec with no redirect to leak.
    if ! : >"$path" 2>/dev/null; then
        CRON_ERR="could not open the lock file $path$([ -e "$path" ] && printf ' -- it exists but is not writable by %s. A lock file created by an earlier root-side write with a 0644 umask does this; fix once with: chmod 664 %s' "$(id -un 2>/dev/null || echo '?')" "$path")"
        return 1
    fi
    # The truncate above creates the file with the CALLER's umask -- and root
    # gets here first on a fresh host (deploy/activate-client take the
    # ACCOUNT's lock as root), leaving a 0644 root-owned file that then
    # permanently refuses the account's own crontab writes. Found live on
    # metropolis pve1 2026-08-06: gen-cron --install as the account failed
    # with "could not open the lock file" after one root-side activate-client
    # had touched the same path. The shared-lock design already scopes WHO
    # shares through the setgid 2775 zfsalert directory; the file itself has
    # to be group-writable for that to mean anything. Best-effort: only the
    # owner may chmod, and a pre-fix foreign 0644 file fails the open above
    # with the exact one-line fix in the message.
    chmod 664 "$path" 2>/dev/null || :
    exec {fd}>"$path"
    if ! flock -w "$CRON_LOCK_TIMEOUT" "$fd"; then
        eval "exec $fd>&-"
        CRON_ERR="could not acquire the crontab lock for '$user' within ${CRON_LOCK_TIMEOUT}s -- another writer is holding it. Refusing to write rather than racing it"
        return 1
    fi
    CRON_LOCK_FD[$user]="$fd"
    return 0
}

cron_lock_release() {   # <user>
    # Two statements, not one `local a=X b=$a`: a single `local` command
    # expands ALL of its words before assigning any of them, so `$user` in the
    # second field would resolve against whatever `user` meant before this
    # call (nothing, under `set -u`) rather than the "$1" just given -- an
    # unbound-variable abort, found by the suite dying with no message because
    # the diagnosing stderr was routed to /dev/null one line below.
    local user="$1"
    local fd="${CRON_LOCK_FD[$user]:-}"
    [ -n "$fd" ] || return 0
    flock -u "$fd" 2>/dev/null
    # See cron_lock_acquire: a bare `exec ... 2>/dev/null` would permanently
    # redirect this process's real stderr to /dev/null, not just silence a
    # close error. $fd is a valid, currently-open descriptor here, so the
    # close does not need a redirect to guard.
    eval "exec $fd>&-"
    unset "CRON_LOCK_FD[$user]"
}


# Read <user>'s crontab into <outfile>, or fail loudly.
#
# "No crontab for user" is EMPTY. Anything else is UNKNOWN, and an unknown
# crontab must never be treated as an empty one -- that is the difference
# between "there is nothing to preserve" and "I could not see what I would be
# destroying". Same rule, same reason, as crontab_of_or_die in zfs-backup.sh.
cron_read() {   # <user> <outfile>  -> 0 ok, 1 unreadable
    local who="$1" out="$2" err rc txt
    err=$(mktemp) || return 1
    if cron_is_self "$who"; then
        txt=$(crontab -l 2>"$err"); rc=$?
    else
        txt=$(crontab -u "$who" -l 2>"$err"); rc=$?
    fi
    if [ "$rc" -ne 0 ] && ! grep -qi "no crontab" "$err"; then
        CRON_ERR="could not read ${who}'s crontab (rc=$rc): $(tr -d '\n' < "$err") -- an unreadable crontab is not an empty one, so nothing has been changed"
        rm -f "$err"
        return 1
    fi
    rm -f "$err"
    # `crontab -l` output never ends without a newline; printf keeps an empty
    # crontab an empty FILE rather than a file holding one blank line.
    if [ -n "$txt" ]; then printf '%s\n' "$txt" > "$out"; else : > "$out"; fi
    return 0
}

# Write <infile> as <user>'s crontab, then READ IT BACK and compare.
#
# `crontab -` can exit 0 having installed something other than what it was
# given (a syntax it silently drops, a quota, a full filesystem). The only
# honest confirmation is to look.
cron_write() {   # <user> <infile>  -> 0 ok, 1 failed
    local who="$1" in="$2" back rc
    if cron_is_self "$who"; then
        crontab "$in" 2>/dev/null; rc=$?
    else
        crontab -u "$who" "$in" 2>/dev/null; rc=$?
    fi
    [ "$rc" -eq 0 ] || { CRON_ERR="crontab(1) refused the new content for '$who' (rc=$rc)"; return 1; }
    back=$(mktemp) || { CRON_ERR="mktemp failed while verifying the write"; return 1; }
    if ! cron_read "$who" "$back"; then rm -f "$back"; return 1; fi
    if ! cmp -s "$in" "$back"; then
        rm -f "$back"
        CRON_ERR="crontab(1) accepted the write for '$who' but reading it back gave something else -- refusing to report success"
        return 1
    fi
    rm -f "$back"
    return 0
}

# Locate <name>'s block in <file>. Non-zero (with CRON_ERR set) when the file is
# MALFORMED for this block -- which is a refusal, never a repair:
#
#   * two BEGINs for one name: which one is the block? Guessing means one of
#     them silently becomes unmanaged text;
#   * BEGIN with no END, or END before BEGIN: the extent is unknown, and every
#     write that follows would be a guess about where somebody else's lines
#     start.
# Sets CRON_B/CRON_E (the marker line numbers, 0/0 when the block is absent)
# instead of echoing them.
#
# Echoing would mean `pos=$(cron_block_locate ...)`, and a command substitution
# is a SUBSHELL: the CRON_ERR explaining a malformed crontab would be set in a
# process that exits immediately, so the caller would refuse with an empty
# reason. Same class of bug as a `die` inside $( ) -- the refusal survives, the
# explanation does not, and the operator is left with a silent failure.
# Validate the WHOLE managed-marker structure, not just the target block's.
#
# REV-20260802-034 F4: counting only the requested name accepts this --
#
#     # BEGIN block-A
#     # BEGIN block-B
#     ...
#     # END block-B
#     # END block-A
#
# -- as a well-formed block-A, and replacing A then deletes the complete B.
# Interleaved markers are worse: they leave an orphan behind. The ownership
# guarantee this library exists for holds only over a non-overlapping layout,
# so the layout is checked before every mutation rather than assumed.
#
# Refused, never repaired: a damaged crontab is a thing for a human to look at,
# and every automatic repair here would be a guess about whose lines are whose.
cron_markers_valid() {   # <file>  -> 0 ok, 1 malformed
    local file="$1" open="" ln name seen=""
    local n=0
    while IFS= read -r ln; do
        n=$((n+1))
        case "$ln" in
            '# BEGIN '*)
                name=${ln#'# BEGIN '}; name=${name%% *}
                cron_block_name_valid "$name" || continue   # not one of ours
                if [ -n "$open" ]; then
                    CRON_ERR="line $n: '# BEGIN $name' opens while '$open' is still open -- managed blocks may not nest or overlap, and replacing the outer one would delete the inner. Repair the crontab by hand; nothing has been changed"
                    return 1
                fi
                case " $seen " in
                    *" $name "*)
                        CRON_ERR="line $n: '$name' has more than one block -- a managed block appears exactly once, and choosing between them would silently orphan the other"
                        return 1 ;;
                esac
                seen="$seen $name"
                open="$name"
                ;;
            '# END '*)
                name=${ln#'# END '}; name=${name%% *}
                cron_block_name_valid "$name" || continue
                if [ -z "$open" ]; then
                    CRON_ERR="line $n: '# END $name' with no open block -- an orphan marker leaves the extent of every later write a guess"
                    return 1
                fi
                if [ "$open" != "$name" ]; then
                    CRON_ERR="line $n: '# END $name' closes while '$open' is open -- interleaved markers. Repair by hand; nothing has been changed"
                    return 1
                fi
                open=""
                ;;
        esac
    done < "$file"
    if [ -n "$open" ]; then
        CRON_ERR="'# BEGIN $open' is never closed -- the block's extent is unknown, so a write would be a guess about where other lines begin"
        return 1
    fi
    return 0
}

cron_block_locate() {   # <file> <name>  -> 0 ok (CRON_B/CRON_E set), 1 malformed
    local file="$1" name="$2"
    local b e
    CRON_B=0; CRON_E=0
    # The global layout first: a target-local check cannot see a foreign block
    # nested inside this one (F4).
    cron_markers_valid "$file" || return 1
    b=$(grep -nE "$(cron_block_begin_re "$name")" "$file" | cut -d: -f1)
    e=$(grep -nE "$(cron_block_end_re "$name")" "$file" | cut -d: -f1)
    local nb ne
    nb=$(printf '%s' "$b" | grep -c . || true)
    ne=$(printf '%s' "$e" | grep -c . || true)
    if [ "$nb" -eq 0 ] && [ "$ne" -eq 0 ]; then return 0; fi
    if [ "$nb" -gt 1 ] || [ "$ne" -gt 1 ]; then
        CRON_ERR="crontab holds $nb '# BEGIN $name' and $ne '# END $name' lines -- a managed block appears exactly once, and repairing this automatically would silently orphan whichever copy was not chosen"
        return 1
    fi
    if [ "$nb" -ne 1 ] || [ "$ne" -ne 1 ]; then
        CRON_ERR="crontab has an unpaired marker for '$name' (BEGIN: ${nb}, END: ${ne}) -- the block's extent is unknown, so a write would be a guess about where other lines begin"
        return 1
    fi
    if [ "$e" -lt "$b" ]; then
        CRON_ERR="crontab has '# END $name' (line $e) before '# BEGIN $name' (line $b)"
        return 1
    fi
    CRON_B="$b"; CRON_E="$e"
    return 0
}


# Render what the crontab WOULD look like with <name>'s block replaced by
# <bodyfile> (or removed, when bodyfile is "-"). Everything outside the block is
# copied byte for byte: this function is the reason a requester cannot damage
# another requester's lines even by accident.
cron_block_render() {   # <curfile> <name> <bodyfile|-> <outfile> <begin_tail>
    local cur="$1" name="$2" body="$3" out="$4" tail="${5:-}"
    local b e
    if ! cron_block_locate "$cur" "$name"; then return 1; fi
    b="$CRON_B"; e="$CRON_E"
    : > "$out" || return 1
    if [ "$b" -gt 0 ]; then
        [ "$b" -gt 1 ] && sed -n "1,$((b-1))p" "$cur" >> "$out"
    else
        cat "$cur" >> "$out"
    fi
    if [ "$body" != "-" ]; then
        # Keep the existing BEGIN tail when re-writing a block that already has
        # one, so adopting a block installed by an older version does not
        # rewrite its header for no reason.
        local begin_line="# BEGIN $name"
        [ -n "$tail" ] && begin_line="# BEGIN $name $tail"
        if [ "$b" -gt 0 ]; then
            local old; old=$(sed -n "${b}p" "$cur")
            [ -n "$old" ] && begin_line="$old"
        fi
        printf '%s\n' "$begin_line" >> "$out"
        cat "$body" >> "$out"
        printf '# END %s\n' "$name" >> "$out"
    fi
    if [ "$b" -gt 0 ]; then
        sed -n "$((e+1)),\$p" "$cur" >> "$out"
    fi
    return 0
}

# A body may not contain marker lines of its own. Nested or duplicated markers
# would make the NEXT locate ambiguous, i.e. this write would break the thing
# that protects the next one.
cron_body_valid() {   # <bodyfile>
    if grep -qE '^# (BEGIN|END) ' "$1"; then
        CRON_ERR="the block body contains its own '# BEGIN'/'# END' marker line, which would make the block's extent ambiguous on the next write"
        return 1
    fi
    return 0
}

# Install <bodyfile> as <name>'s block in <user>'s crontab.
#
# Everything outside the block survives byte for byte. On ANY failure the
# crontab is restored to exactly what it was, and the function reports the
# restore separately from the original failure -- "the write failed" and "the
# write failed and I could not put it back" are different emergencies.
cron_block_install() {   # <user> <name> <bodyfile> [begin_tail]
    local who="$1"
    cron_lock_acquire "$who" || return 1
    cron_block_install_impl "$@"; local rc=$?
    cron_lock_release "$who"
    return "$rc"
}
cron_block_install_impl() {
    local who="$1" name="$2" body="$3" tail="${4:-}"
    CRON_ERR=""
    cron_block_name_valid "$name" || { CRON_ERR="invalid block name '$name'"; return 1; }
    [ -r "$body" ] || { CRON_ERR="cannot read block body '$body'"; return 1; }
    cron_body_valid "$body" || return 1
    local cur new
    cur=$(mktemp) || { CRON_ERR="mktemp failed"; return 1; }
    new=$(mktemp) || { rm -f "$cur"; CRON_ERR="mktemp failed"; return 1; }
    if ! cron_read "$who" "$cur"; then rm -f "$cur" "$new"; return 1; fi
    if ! cron_paused_guard "$cur" "$name"; then rm -f "$cur" "$new"; return 1; fi
    if ! cron_block_render "$cur" "$name" "$body" "$new" "$tail"; then rm -f "$cur" "$new"; return 1; fi
    if cmp -s "$cur" "$new"; then
        rm -f "$cur" "$new"
        CRON_CHANGED=0
        return 0
    fi
    if ! cron_write "$who" "$new"; then
        cron_restore_after_failure "$who" "$cur" "$CRON_ERR"; local rc=$?
        rm -f "$new"
        [ "$rc" -eq 2 ] || rm -f "$cur"
        return "$rc"
    fi
    rm -f "$cur" "$new"
    CRON_CHANGED=1
    return 0
}

# Decide what a failed write actually did, before shouting about it.
#
# `crontab -` refusing its input is the COMMON case (a syntax error, a full
# disk) and it leaves the crontab untouched -- there is nothing to restore, and
# announcing "THE RESTORE ALSO FAILED" for a crontab that was never modified is
# a false emergency. So look first: if the crontab still equals what we read,
# the write simply did not happen.
#
# Only a crontab that DID change needs restoring, and only a restore that
# cannot be verified is the real alarm -- exit 2, prior content left on disk.
cron_restore_after_failure() {   # <user> <curfile> <original error>
    local who="$1" cur="$2" first="$3" now
    now=$(mktemp) || { CRON_ERR="$first -- and a temporary file could not be made to check what the crontab now holds"; return 2; }
    if cron_read "$who" "$now" && cmp -s "$cur" "$now"; then
        rm -f "$now"
        CRON_ERR="$first -- the crontab was not modified"
        return 1
    fi
    rm -f "$now"
    if cron_write "$who" "$cur"; then
        CRON_ERR="$first -- the crontab has been restored to its prior state"
        return 1
    fi
    CRON_ERR="$first -- AND THE RESTORE ALSO FAILED. ${who}'s crontab may be in an unknown state; the prior content is in $cur"
    return 2
}

# Remove <name>'s block entirely. Absent block is success and no change: this
# is called on teardown paths, where "it was already gone" is the goal state,
# not an error.
cron_block_remove() {   # <user> <name>
    local who="$1"
    cron_lock_acquire "$who" || return 1
    cron_block_remove_impl "$@"; local rc=$?
    cron_lock_release "$who"
    return "$rc"
}
cron_block_remove_impl() {
    local who="$1" name="$2"
    CRON_ERR=""
    cron_block_name_valid "$name" || { CRON_ERR="invalid block name '$name'"; return 1; }
    local cur new
    cur=$(mktemp) || { CRON_ERR="mktemp failed"; return 1; }
    new=$(mktemp) || { rm -f "$cur"; CRON_ERR="mktemp failed"; return 1; }
    if ! cron_read "$who" "$cur"; then rm -f "$cur" "$new"; return 1; fi
    if ! cron_paused_guard "$cur" "$name"; then rm -f "$cur" "$new"; return 1; fi
    if ! cron_block_render "$cur" "$name" "-" "$new" ""; then rm -f "$cur" "$new"; return 1; fi
    if cmp -s "$cur" "$new"; then rm -f "$cur" "$new"; CRON_CHANGED=0; return 0; fi
    if ! cron_write "$who" "$new"; then
        cron_restore_after_failure "$who" "$cur" "$CRON_ERR"; local rc=$?
        rm -f "$new"
        [ "$rc" -eq 2 ] || rm -f "$cur"
        return "$rc"
    fi
    rm -f "$cur" "$new"
    CRON_CHANGED=1
    return 0
}


# Make sure ONE line exists inside <name>'s block, and adopt any loose copy of
# it that is living outside the block.
#
# This is the shape deploy.sh's four hand-rolled sites had -- "if the crontab
# already mentions this script, leave it alone, otherwise append it" -- with the
# two things that were missing from it:
#
#   * the line goes INSIDE a managed block, so a later teardown or migration can
#     tell whose it is. Two of deploy.sh's lines were loose in root's crontab,
#     indistinguishable from something a human typed, and therefore impossible
#     to remove, move or audit without guessing;
#   * a loose copy is MOVED rather than left to run twice. Appending the managed
#     copy next to an unmanaged one would double the schedule, which is exactly
#     the failure gen-cron.sh refuses to risk with its own conflict check.
#
# <match> is a FIXED STRING (grep -F), and it decides both questions: which
# existing line is "this line", and which loose line gets adopted. Callers pass
# the same identifying substring they used to grep for before -- the script's
# path -- so adoption cannot reach further than the old detection did.
#
# Everything else in the crontab, inside the block or outside it, is untouched.
# <also> (optional, newline-separated fixed strings) names OTHER shapes of the
# same job -- older spellings this program has emitted over time. They are
# dropped wherever they are found, inside the block or loose, so normalising an
# obsolete line is the same operation as installing the current one. deploy.sh
# needs it: its updater line has had three shapes, and leaving one of them next
# to the current one would run the update twice an hour.
cron_block_ensure_line() {   # <user> <name> <match> <line> [begin_tail] [also]
    local who="$1"
    cron_lock_acquire "$who" || return 1
    cron_block_ensure_line_impl "$@"; local rc=$?
    cron_lock_release "$who"
    return "$rc"
}
cron_block_ensure_line_impl() {
    local who="$1" name="$2" match="$3" line="$4" tail="${5:-}" also="${6:-}"
    CRON_ERR=""; CRON_ADOPTED=0
    cron_block_name_valid "$name" || { CRON_ERR="invalid block name '$name'"; return 1; }
    [ -n "$match" ] || { CRON_ERR="cron_block_ensure_line needs a non-empty match string"; return 1; }

    local cur body new
    cur=$(mktemp) || { CRON_ERR="mktemp failed"; return 1; }
    body=$(mktemp) || { rm -f "$cur"; CRON_ERR="mktemp failed"; return 1; }
    new=$(mktemp) || { rm -f "$cur" "$body"; CRON_ERR="mktemp failed"; return 1; }
    if ! cron_read "$who" "$cur"; then rm -f "$cur" "$body" "$new"; return 1; fi
    if ! cron_paused_guard "$cur" "$name"; then rm -f "$cur" "$body" "$new"; return 1; fi
    if ! cron_block_locate "$cur" "$name"; then rm -f "$cur" "$body" "$new"; return 1; fi

    # Every spelling this job has ever had, as fixed strings.
    local matches; matches=$(mktemp) || { rm -f "$cur" "$body" "$new"; CRON_ERR="mktemp failed"; return 1; }
    printf '%s\n' "$match" > "$matches"
    [ -n "$also" ] && printf '%s\n' "$also" | grep -v '^$' >> "$matches"

    # The block's body, minus every previous version of this line.
    if [ "$CRON_B" -gt 0 ] && [ "$CRON_E" -gt $((CRON_B+1)) ]; then
        sed -n "$((CRON_B+1)),$((CRON_E-1))p" "$cur" | grep -vFf "$matches" > "$body" || :
    fi
    printf '%s\n' "$line" >> "$body"

    # Render the block first, then drop loose copies from the result -- doing it
    # in this order means the line we just placed is inside the block and cannot
    # be matched as "loose" by the same pattern.
    local staged; staged=$(mktemp) || { rm -f "$cur" "$body" "$new"; CRON_ERR="mktemp failed"; return 1; }
    if ! cron_block_render "$cur" "$name" "$body" "$staged" "$tail"; then
        rm -f "$cur" "$body" "$new" "$staged"; return 1
    fi
    if ! cron_block_locate "$staged" "$name"; then rm -f "$cur" "$body" "$new" "$staged"; return 1; fi
    awk -v b="$CRON_B" -v e="$CRON_E" -v mf="$matches" '
        BEGIN { while ((getline ln < mf) > 0) if (ln != "") pat[++n] = ln }
        NR>=b && NR<=e { print; next }
        { for (i=1; i<=n; i++) if (index($0, pat[i]) > 0) next; print }' "$staged" > "$new"
    CRON_ADOPTED=$(( $(grep -cFf "$matches" "$staged") - $(grep -cFf "$matches" "$new") ))
    rm -f "$staged" "$body" "$matches"

    if cmp -s "$cur" "$new"; then rm -f "$cur" "$new"; CRON_CHANGED=0; return 0; fi
    if ! cron_write "$who" "$new"; then
        cron_restore_after_failure "$who" "$cur" "$CRON_ERR"; local rc=$?
        rm -f "$new"
        [ "$rc" -eq 2 ] || rm -f "$cur"
        return "$rc"
    fi
    rm -f "$cur" "$new"
    CRON_CHANGED=1
    return 0
}

# Like cron_block_ensure_line, but KEEPS an existing line's exact text.
#
# The difference matters and is not cosmetic. deploy.sh's capacity and auto-pull
# sites say "already present, leaving it alone" -- which is a promise that a
# schedule someone tuned by hand survives a re-run of the provisioner. Moving
# such a line into the managed block must not silently rewrite it back to the
# default, or the first thing this unification would do on a live host is undo
# an operator's edit.
#
# So: if any line matches, the FIRST one's text is what lands in the block;
# only when nothing matches is <default line> used. The updater line is the
# deliberate exception and uses cron_block_ensure_line, because normalising
# three historical spellings to one is the whole point there.
cron_block_adopt_line() {   # <user> <name> <match> <default line> [begin_tail]
    local who="$1"
    cron_lock_acquire "$who" || return 1
    cron_block_adopt_line_impl "$@"; local rc=$?
    cron_lock_release "$who"
    return "$rc"
}
cron_block_adopt_line_impl() {
    local who="$1" name="$2" match="$3" line="$4" tail="${5:-}"
    CRON_ERR=""
    local cur found
    cur=$(mktemp) || { CRON_ERR="mktemp failed"; return 1; }
    if ! cron_read "$who" "$cur"; then rm -f "$cur"; return 1; fi
    found=$(grep -m1 -F -- "$match" "$cur" || true)
    rm -f "$cur"
    [ -n "$found" ] && line="$found"
    # ...ensure_line's IMPL directly, never the locked wrapper: this process
    # already holds who's lock, and flock would self-deadlock reacquiring it.
    cron_block_ensure_line_impl "$who" "$name" "$match" "$line" "$tail"
}


# Replace <user>'s ENTIRE crontab with <infile>, verified. The whole-crontab
# primitive, for a change that cannot be expressed as one named block's
# replace/remove -- e.g. "a whole crontab minus one collector block".
#
# UNLOCKED: the caller holds the cron lock. deploy.sh installs several blocks
# under ONE lock, calling this once per block, so a later block's failure can
# never leave a half-written crontab behind an already-released lock.
#
# Refuses a target whose markers are malformed (F4): installing an already-
# broken layout would make the FIRST ordinary block write after it guess where
# somebody else's lines start -- the guardrail against a rendered crontab that
# itself violates the one-block-per-name invariant, a bug in the CALLER's
# renderer. Goes through the same write/read-back path as every other write.
cron_replace_all_impl() {
    local who="$1" in="$2"
    CRON_ERR=""
    [ -r "$in" ] || { CRON_ERR="cannot read '$in'"; return 1; }
    cron_markers_valid "$in" || return 1
    cron_write "$who" "$in"
}
