#!/bin/bash
###############################################################################
# lib-cron.sh -- the ONE way this project writes a crontab.
#
# WHY THIS FILE EXISTS
#
# Until 2026-08-02 three programs wrote crontabs and none of them shared a line
# of code:
#
#   deploy.sh      four hand-rolled `crontab -l | ... | crontab -` sites
#                  (self-update line, capacity line, the account's auto-pull
#                  line, and a removal path), each of which REWRITES THE WHOLE
#                  crontab to add or drop one line;
#   gen-cron.sh    the `# BEGIN/END zfs-backup-managed` block;
#   zfs-backup.sh  the `# BEGIN/END zfs-backup-host` block, plus its own
#                  backup/restore around gen-cron.sh --install.
#
# Two of deploy.sh's lines were not inside any block at all -- loose in the
# crontab, indistinguishable from something a human put there, protected only
# by every other writer being careful to copy what it did not recognise.
#
# That design has already cost this project twice: a crontab was wiped during a
# live test (`$0` vs `BASH_SOURCE[0]`), and metropolis pve2 ran four minutes
# with no backup jobs when one writer's block came out before another's went in.
# The six assertions in zfs-backup.sh (assert_target_block_not_clobbered,
# assert_no_foreign_managed_block, assert_cron_config_matches_installed,
# crontab_of_or_die, managed_block_fingerprint, job_identity) are compensating
# controls for exactly this: they exist to keep writers from eating each other.
#
# So: ONE writer, several requesters. Each requester owns a NAMED BLOCK and can
# touch nothing else -- not because it promises not to, but because the only
# entry point takes the block name as an argument and refuses to write outside
# it.
#
# WHAT THIS FILE DOES NOT DO
#
# It does not know what a cron line means, which account should run it, or
# whether the job it names exists. That stays with the requester. This file
# answers exactly one question: how do you replace one named region of a
# crontab without losing the rest of it.
#
# Sourced by deploy.sh, gen-cron.sh and zfs-backup.sh. Deliberately NOT part of
# lib-zfs-snap.sh: that library is the send/receive/quiesce engine and is
# sourced by the transfer scripts, which never write a crontab.
#
# update-control.sh keeps its own duplicated helpers on purpose (it must survive
# a rollback of the repo it lives outside of) and does not source this file.
###############################################################################

# Marker lines. BEGIN carries a human-readable tail after the name -- the
# installed crontabs already look like this, and matching must not depend on
# that tail, or adopting an existing block would fail:
#
#   # BEGIN zfs-backup-managed (generated by gen-cron.sh -- do not hand-edit...)
#   # END zfs-backup-managed
cron_block_begin_re() { printf '^# BEGIN %s(\\b|$)' "$1"; }
cron_block_end_re()   { printf '^# END %s[[:space:]]*$' "$1"; }

# A block name is a path component of the crontab's namespace, so it gets the
# same treatment every other externally-supplied identifier in this project
# gets: validated, never interpolated on trust.
cron_block_name_valid() {   # <name>
    case "$1" in
        ""|*[!A-Za-z0-9._-]*) return 1 ;;
        *) return 0 ;;
    esac
}

# Read <user>'s crontab into <outfile>, or fail loudly.
#
# "No crontab for user" is EMPTY. Anything else is UNKNOWN, and an unknown
# crontab must never be treated as an empty one -- that is the difference
# between "there is nothing to preserve" and "I could not see what I would be
# destroying". Same rule, same reason, as crontab_of_or_die in zfs-backup.sh.
cron_read() {   # <user> <outfile>  -> 0 ok, 1 unreadable
    local who="$1" out="$2" err rc txt
    err=$(mktemp) || return 1
    if [ "$who" = "$(id -un)" ] || { [ "$(id -u)" = 0 ] && [ "$who" = root ]; }; then
        txt=$(crontab -l 2>"$err"); rc=$?
    else
        txt=$(crontab -u "$who" -l 2>"$err"); rc=$?
    fi
    if [ "$rc" -ne 0 ] && ! grep -qi "no crontab" "$err"; then
        CRON_ERR="could not read ${who}'s crontab (rc=$rc): $(tr -d '\n' < "$err") -- an unreadable crontab is not an empty one, so nothing has been changed"
        rm -f "$err"
        return 1
    fi
    rm -f "$err"
    # `crontab -l` output never ends without a newline; printf keeps an empty
    # crontab an empty FILE rather than a file holding one blank line.
    if [ -n "$txt" ]; then printf '%s\n' "$txt" > "$out"; else : > "$out"; fi
    return 0
}

# Write <infile> as <user>'s crontab, then READ IT BACK and compare.
#
# `crontab -` can exit 0 having installed something other than what it was
# given (a syntax it silently drops, a quota, a full filesystem). The only
# honest confirmation is to look.
cron_write() {   # <user> <infile>  -> 0 ok, 1 failed
    local who="$1" in="$2" back rc
    if [ "$who" = "$(id -un)" ] || { [ "$(id -u)" = 0 ] && [ "$who" = root ]; }; then
        crontab "$in" 2>/dev/null; rc=$?
    else
        crontab -u "$who" "$in" 2>/dev/null; rc=$?
    fi
    [ "$rc" -eq 0 ] || { CRON_ERR="crontab(1) refused the new content for '$who' (rc=$rc)"; return 1; }
    back=$(mktemp) || { CRON_ERR="mktemp failed while verifying the write"; return 1; }
    if ! cron_read "$who" "$back"; then rm -f "$back"; return 1; fi
    if ! cmp -s "$in" "$back"; then
        rm -f "$back"
        CRON_ERR="crontab(1) accepted the write for '$who' but reading it back gave something else -- refusing to report success"
        return 1
    fi
    rm -f "$back"
    return 0
}

# Locate <name>'s block in <file>. Non-zero (with CRON_ERR set) when the file is
# MALFORMED for this block -- which is a refusal, never a repair:
#
#   * two BEGINs for one name: which one is the block? Guessing means one of
#     them silently becomes unmanaged text;
#   * BEGIN with no END, or END before BEGIN: the extent is unknown, and every
#     write that follows would be a guess about where somebody else's lines
#     start.
# Sets CRON_B/CRON_E (the marker line numbers, 0/0 when the block is absent)
# instead of echoing them.
#
# Echoing would mean `pos=$(cron_block_locate ...)`, and a command substitution
# is a SUBSHELL: the CRON_ERR explaining a malformed crontab would be set in a
# process that exits immediately, so the caller would refuse with an empty
# reason. Same class of bug as a `die` inside $( ) -- the refusal survives, the
# explanation does not, and the operator is left with a silent failure.
cron_block_locate() {   # <file> <name>  -> 0 ok (CRON_B/CRON_E set), 1 malformed
    local file="$1" name="$2"
    local b e
    CRON_B=0; CRON_E=0
    b=$(grep -nE "$(cron_block_begin_re "$name")" "$file" | cut -d: -f1)
    e=$(grep -nE "$(cron_block_end_re "$name")" "$file" | cut -d: -f1)
    local nb ne
    nb=$(printf '%s' "$b" | grep -c . || true)
    ne=$(printf '%s' "$e" | grep -c . || true)
    if [ "$nb" -eq 0 ] && [ "$ne" -eq 0 ]; then return 0; fi
    if [ "$nb" -gt 1 ] || [ "$ne" -gt 1 ]; then
        CRON_ERR="crontab holds $nb '# BEGIN $name' and $ne '# END $name' lines -- a managed block appears exactly once, and repairing this automatically would silently orphan whichever copy was not chosen"
        return 1
    fi
    if [ "$nb" -ne 1 ] || [ "$ne" -ne 1 ]; then
        CRON_ERR="crontab has an unpaired marker for '$name' (BEGIN: ${nb}, END: ${ne}) -- the block's extent is unknown, so a write would be a guess about where other lines begin"
        return 1
    fi
    if [ "$e" -lt "$b" ]; then
        CRON_ERR="crontab has '# END $name' (line $e) before '# BEGIN $name' (line $b)"
        return 1
    fi
    CRON_B="$b"; CRON_E="$e"
    return 0
}

# The block's body, without its markers. Empty output for an absent block, so
# callers distinguish "absent" from "present but empty" by the return of
# cron_block_locate, not by the text.
cron_block_read() {   # <user> <name>
    local who="$1" name="$2" cur
    cron_block_name_valid "$name" || { CRON_ERR="invalid block name '$name'"; return 1; }
    cur=$(mktemp) || return 1
    cron_read "$who" "$cur" || { rm -f "$cur"; return 1; }
    if ! cron_block_locate "$cur" "$name"; then rm -f "$cur"; return 1; fi
    if [ "$CRON_B" -gt 0 ] && [ "$CRON_E" -gt $((CRON_B+1)) ]; then
        sed -n "$((CRON_B+1)),$((CRON_E-1))p" "$cur"
    fi
    rm -f "$cur"
    return 0
}

# Render what the crontab WOULD look like with <name>'s block replaced by
# <bodyfile> (or removed, when bodyfile is "-"). Everything outside the block is
# copied byte for byte: this function is the reason a requester cannot damage
# another requester's lines even by accident.
cron_block_render() {   # <curfile> <name> <bodyfile|-> <outfile> <begin_tail>
    local cur="$1" name="$2" body="$3" out="$4" tail="${5:-}"
    local b e
    if ! cron_block_locate "$cur" "$name"; then return 1; fi
    b="$CRON_B"; e="$CRON_E"
    : > "$out" || return 1
    if [ "$b" -gt 0 ]; then
        [ "$b" -gt 1 ] && sed -n "1,$((b-1))p" "$cur" >> "$out"
    else
        cat "$cur" >> "$out"
    fi
    if [ "$body" != "-" ]; then
        # Keep the existing BEGIN tail when re-writing a block that already has
        # one, so adopting a block installed by an older version does not
        # rewrite its header for no reason.
        local begin_line="# BEGIN $name"
        [ -n "$tail" ] && begin_line="# BEGIN $name $tail"
        if [ "$b" -gt 0 ]; then
            local old; old=$(sed -n "${b}p" "$cur")
            [ -n "$old" ] && begin_line="$old"
        fi
        printf '%s\n' "$begin_line" >> "$out"
        cat "$body" >> "$out"
        printf '# END %s\n' "$name" >> "$out"
    fi
    if [ "$b" -gt 0 ]; then
        sed -n "$((e+1)),\$p" "$cur" >> "$out"
    fi
    return 0
}

# A body may not contain marker lines of its own. Nested or duplicated markers
# would make the NEXT locate ambiguous, i.e. this write would break the thing
# that protects the next one.
cron_body_valid() {   # <bodyfile>
    if grep -qE '^# (BEGIN|END) ' "$1"; then
        CRON_ERR="the block body contains its own '# BEGIN'/'# END' marker line, which would make the block's extent ambiguous on the next write"
        return 1
    fi
    return 0
}

# Install <bodyfile> as <name>'s block in <user>'s crontab.
#
# Everything outside the block survives byte for byte. On ANY failure the
# crontab is restored to exactly what it was, and the function reports the
# restore separately from the original failure -- "the write failed" and "the
# write failed and I could not put it back" are different emergencies.
cron_block_install() {   # <user> <name> <bodyfile> [begin_tail]
    local who="$1" name="$2" body="$3" tail="${4:-}"
    CRON_ERR=""
    cron_block_name_valid "$name" || { CRON_ERR="invalid block name '$name'"; return 1; }
    [ -r "$body" ] || { CRON_ERR="cannot read block body '$body'"; return 1; }
    cron_body_valid "$body" || return 1
    local cur new
    cur=$(mktemp) || { CRON_ERR="mktemp failed"; return 1; }
    new=$(mktemp) || { rm -f "$cur"; CRON_ERR="mktemp failed"; return 1; }
    if ! cron_read "$who" "$cur"; then rm -f "$cur" "$new"; return 1; fi
    if ! cron_block_render "$cur" "$name" "$body" "$new" "$tail"; then rm -f "$cur" "$new"; return 1; fi
    if cmp -s "$cur" "$new"; then
        rm -f "$cur" "$new"
        CRON_CHANGED=0
        return 0
    fi
    if ! cron_write "$who" "$new"; then
        cron_restore_after_failure "$who" "$cur" "$CRON_ERR"; local rc=$?
        rm -f "$new"
        [ "$rc" -eq 2 ] || rm -f "$cur"
        return "$rc"
    fi
    rm -f "$cur" "$new"
    CRON_CHANGED=1
    return 0
}

# Decide what a failed write actually did, before shouting about it.
#
# `crontab -` refusing its input is the COMMON case (a syntax error, a full
# disk) and it leaves the crontab untouched -- there is nothing to restore, and
# announcing "THE RESTORE ALSO FAILED" for a crontab that was never modified is
# a false emergency. So look first: if the crontab still equals what we read,
# the write simply did not happen.
#
# Only a crontab that DID change needs restoring, and only a restore that
# cannot be verified is the real alarm -- exit 2, prior content left on disk.
cron_restore_after_failure() {   # <user> <curfile> <original error>
    local who="$1" cur="$2" first="$3" now
    now=$(mktemp) || { CRON_ERR="$first -- and a temporary file could not be made to check what the crontab now holds"; return 2; }
    if cron_read "$who" "$now" && cmp -s "$cur" "$now"; then
        rm -f "$now"
        CRON_ERR="$first -- the crontab was not modified"
        return 1
    fi
    rm -f "$now"
    if cron_write "$who" "$cur"; then
        CRON_ERR="$first -- the crontab has been restored to its prior state"
        return 1
    fi
    CRON_ERR="$first -- AND THE RESTORE ALSO FAILED. ${who}'s crontab may be in an unknown state; the prior content is in $cur"
    return 2
}

# Remove <name>'s block entirely. Absent block is success and no change: this
# is called on teardown paths, where "it was already gone" is the goal state,
# not an error.
cron_block_remove() {   # <user> <name>
    local who="$1" name="$2"
    CRON_ERR=""
    cron_block_name_valid "$name" || { CRON_ERR="invalid block name '$name'"; return 1; }
    local cur new
    cur=$(mktemp) || { CRON_ERR="mktemp failed"; return 1; }
    new=$(mktemp) || { rm -f "$cur"; CRON_ERR="mktemp failed"; return 1; }
    if ! cron_read "$who" "$cur"; then rm -f "$cur" "$new"; return 1; fi
    if ! cron_block_render "$cur" "$name" "-" "$new" ""; then rm -f "$cur" "$new"; return 1; fi
    if cmp -s "$cur" "$new"; then rm -f "$cur" "$new"; CRON_CHANGED=0; return 0; fi
    if ! cron_write "$who" "$new"; then
        cron_restore_after_failure "$who" "$cur" "$CRON_ERR"; local rc=$?
        rm -f "$new"
        [ "$rc" -eq 2 ] || rm -f "$cur"
        return "$rc"
    fi
    rm -f "$cur" "$new"
    CRON_CHANGED=1
    return 0
}

# What would change, without changing it. Printed to an operator before any
# managed write, because every incident this file exists to prevent was a write
# nobody looked at first.
cron_block_diff() {   # <user> <name> <bodyfile|->  -> prints a diff, 0 if identical
    local who="$1" name="$2" body="$3"
    CRON_ERR=""
    local cur new
    cur=$(mktemp) || return 1
    new=$(mktemp) || { rm -f "$cur"; return 1; }
    if ! cron_read "$who" "$cur"; then rm -f "$cur" "$new"; return 1; fi
    if ! cron_block_render "$cur" "$name" "$body" "$new" ""; then rm -f "$cur" "$new"; return 1; fi
    if cmp -s "$cur" "$new"; then rm -f "$cur" "$new"; return 0; fi
    diff -u --label "crontab($who) now" --label "crontab($who) after" "$cur" "$new" || :
    rm -f "$cur" "$new"
    return 1
}
