#!/bin/bash
# Unit tests for lib-cron.sh -- the single crontab writer.
#
# NEVER touches a real crontab. `crontab` is a stub on PATH backed by a file per
# user, so the suite can simulate an unreadable crontab, a refusing crontab(1),
# and a crontab(1) that accepts a write and stores something else -- the three
# failure shapes the library exists to survive.
#
# Runs anywhere: no root, no ZFS, no cron daemon.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
LIB="${LIB:-$REPO/lib-cron.sh}"
[ -r "$LIB" ] || { echo "cannot read lib-cron.sh at $LIB" >&2; exit 1; }

TMPD="$(mktemp -d)"
trap 'rm -rf "$TMPD"' EXIT
mkdir -p "$TMPD/bin" "$TMPD/tabs"

PASS=0; FAIL=0
check() {   # <desc> <want> <got>
    local d="$1" w="$2" g="$3"
    if [ "$g" = "$w" ]; then echo "PASS $d"; PASS=$((PASS+1))
    else echo "FAIL $d"; echo "     want: [$w]"; echo "     got:  [$g]"; FAIL=$((FAIL+1)); fi
}
ok()  { echo "PASS $1"; PASS=$((PASS+1)); }
bad() { echo "FAIL $1"; echo "     $2"; FAIL=$((FAIL+1)); }

# ---- the crontab stub -------------------------------------------------------
#
# CRONTAB_MODE steers it:
#   ok         normal
#   unreadable `-l` fails with something that is NOT "no crontab"
#   refuse     writes fail
#   liar       writes succeed but store something else (the case that makes a
#              read-back the only honest confirmation)
cat > "$TMPD/bin/crontab" <<'EOF'
#!/bin/bash
d="${CRONTAB_DIR:?}"; mode="${CRONTAB_MODE:-ok}"
u="$(id -un)"
if [ "${1:-}" = "-u" ]; then u="$2"; shift 2; fi
f="$d/$u"
if [ "${1:-}" = "-l" ]; then
    [ "$mode" = unreadable ] && { echo "crontab: cannot read from database" >&2; exit 1; }
    [ -f "$f" ] || { echo "no crontab for $u" >&2; exit 1; }
    cat "$f"; exit 0
fi
[ "$mode" = refuse ] && { echo "crontab: errors in crontab file" >&2; exit 1; }
if [ "$mode" = liar ]; then cat "${1:?}" > "$f"; echo "# something else" >> "$f"; exit 0; fi
cat "${1:?}" > "$f"; exit 0
EOF
chmod +x "$TMPD/bin/crontab"
export PATH="$TMPD/bin:$PATH" CRONTAB_DIR="$TMPD/tabs" CRONTAB_MODE=ok

# shellcheck disable=SC1090
source "$LIB"

ME="$(id -un)"
tab() { printf '%s' "$TMPD/tabs/$ME"; }
seed() { printf '%s\n' "$@" > "$(tab)"; }
body() { printf '%s\n' "$@" > "$TMPD/body"; printf '%s' "$TMPD/body"; }
none() { rm -f "$(tab)"; }

# ---- A. the block is created, replaced and removed in place -----------------
none
cron_block_install "$ME" zfs-backup-host "$(body '0 8 * * * capacity')" "(host-level jobs)"
check "A1 install into an empty crontab: rc" "0" "$?"
check "A1 ...creates the block" \
      "# BEGIN zfs-backup-host (host-level jobs)|0 8 * * * capacity|# END zfs-backup-host" \
      "$(tr '\n' '|' < "$(tab)" | sed 's/|$//')"

cron_block_install "$ME" zfs-backup-host "$(body '0 9 * * * capacity')"
check "A2 replacing the body keeps the block in place" \
      "# BEGIN zfs-backup-host (host-level jobs)|0 9 * * * capacity|# END zfs-backup-host" \
      "$(tr '\n' '|' < "$(tab)" | sed 's/|$//')"
check "A2 ...and the original BEGIN tail is preserved, not rewritten" "1" \
      "$(grep -c 'BEGIN zfs-backup-host (host-level jobs)' "$(tab)")"

cron_block_install "$ME" zfs-backup-host "$(body '0 9 * * * capacity')"
check "A3 an identical install is a no-op" "0" "${CRON_CHANGED}"

cron_block_remove "$ME" zfs-backup-host
check "A4 remove takes the whole block" "0" "$(grep -c 'zfs-backup-host' "$(tab)")"
cron_block_remove "$ME" zfs-backup-host
check "A5 removing an absent block is success, no change" "0" "${CRON_CHANGED}"

# ---- B. everything outside the block is preserved byte for byte -------------
#
# This is the property the whole file exists for. A human's line, another
# requester's block, and a comment must all survive a write they had nothing to
# do with.
seed \
  '# a human wrote this' \
  '30 3 * * * /usr/local/bin/whatever' \
  '# BEGIN zfs-backup-managed (generated by gen-cron.sh)' \
  '1 * * * * snapsend' \
  '# END zfs-backup-managed' \
  'MAILTO=""' \
  '0 8 * * * capacity-loose'
before=$(cat "$(tab)")
cron_block_install "$ME" zfs-backup-host "$(body '0 7 * * * digest')"
check "B1 the foreign managed block is untouched" "1" \
      "$(grep -c '^1 \* \* \* \* snapsend$' "$(tab)")"
check "B2 the human's line survives" "1" "$(grep -c 'whatever' "$(tab)")"
check "B3 the loose line survives" "1" "$(grep -c 'capacity-loose' "$(tab)")"
check "B4 MAILTO survives" "1" "$(grep -c '^MAILTO' "$(tab)")"
check "B5 nothing but the new block was added" "1" \
      "$(( $(wc -l < "$(tab)") - $(printf '%s\n' "$before" | wc -l) - 2 ))"

# ...and writing the OTHER block does not disturb this one either.
cron_block_install "$ME" zfs-backup-managed "$(body '2 * * * * snapget')"
check "B6 replacing the managed block leaves the host block alone" "1" \
      "$(grep -c '0 7 \* \* \* digest' "$(tab)")"
check "B7 ...and actually replaced the managed body" "1" \
      "$(grep -c '2 \* \* \* \* snapget' "$(tab)")"
check "B8 ...without duplicating its markers" "1" \
      "$(grep -c '^# BEGIN zfs-backup-managed' "$(tab)")"

# ---- C. malformed markers are refused, never repaired -----------------------
#
# Guessing which of two BEGIN lines is "the" block silently orphans the other;
# an unpaired marker means the block's extent is unknown, so every following
# write would be a guess about where somebody else's lines start.
seed '# BEGIN zfs-backup-host' 'a' '# END zfs-backup-host' '# BEGIN zfs-backup-host' 'b' '# END zfs-backup-host'
cron_block_install "$ME" zfs-backup-host "$(body 'x')"
check "C1 two blocks of the same name: refused" "1" "$?"
case "$CRON_ERR" in *"appears exactly once"*) ok "C1 ...with a reason that names the rule" ;;
  *) bad "C1 ...with a reason that names the rule" "$CRON_ERR" ;; esac
check "C2 ...and nothing was written" "2" "$(grep -c '^# BEGIN' "$(tab)")"

seed '# BEGIN zfs-backup-host' 'a'
cron_block_install "$ME" zfs-backup-host "$(body 'x')"
check "C3 BEGIN without END: refused" "1" "$?"
case "$CRON_ERR" in *"unpaired"*) ok "C3 ...named as unpaired" ;;
  *) bad "C3 ...named as unpaired" "$CRON_ERR" ;; esac

seed '# END zfs-backup-host' 'a' '# BEGIN zfs-backup-host'
cron_block_install "$ME" zfs-backup-host "$(body 'x')"
check "C4 END before BEGIN: refused" "1" "$?"

# A body carrying its own markers would make the NEXT locate ambiguous -- i.e.
# this write would break the guard protecting the following one.
seed 'x'
cron_block_install "$ME" zfs-backup-host "$(body '# BEGIN something' '1 * * * * job')"
check "C5 a body with marker lines is refused" "1" "$?"
case "$CRON_ERR" in *ambiguous*) ok "C5 ...because the extent would become ambiguous" ;;
  *) bad "C5 ...because the extent would become ambiguous" "$CRON_ERR" ;; esac

check "C6 an invalid block name is refused" "1" \
      "$(cron_block_install "$ME" 'bad name;rm -rf' "$(body 'x')" >/dev/null 2>&1; echo $?)"

# ---- D. an unreadable crontab is not an empty one ---------------------------
#
# The distinction the whole project keeps re-learning: "there is nothing to
# preserve" and "I cannot see what I would destroy" are different answers.
seed '0 1 * * * important'
CRONTAB_MODE=unreadable
cron_block_install "$ME" zfs-backup-host "$(body 'x')"
check "D1 unreadable crontab: refused" "1" "$?"
case "$CRON_ERR" in *"not an empty one"*) ok "D1 ...and says why" ;;
  *) bad "D1 ...and says why" "$CRON_ERR" ;; esac
CRONTAB_MODE=ok
check "D2 ...and the crontab was left alone" "1" "$(grep -c important "$(tab)")"

# An ABSENT crontab, though, is genuinely empty and must work.
none
CRONTAB_MODE=ok
cron_block_install "$ME" zfs-backup-host "$(body '1 * * * * first')"
check "D3 absent crontab is treated as empty, not unreadable" "0" "$?"
check "D3 ...and the block lands" "1" "$(grep -c 'first' "$(tab)")"

# ---- E. a failed write restores the prior state -----------------------------
seed '0 1 * * * important' '# BEGIN zfs-backup-host' 'old' '# END zfs-backup-host'
CRONTAB_MODE=refuse
cron_block_install "$ME" zfs-backup-host "$(body 'new')"
rc=$?
CRONTAB_MODE=ok
check "E1 a refusing crontab(1) is a failure, not a silent skip" "1" "$rc"
# ...and it is NOT the loud one. A refused write leaves the crontab untouched,
# so there is nothing to restore; announcing a failed restore for a crontab that
# was never modified is a false emergency, and the next real one gets ignored.
check "E2 ...the prior content is intact" "1" "$(grep -c '^old$' "$(tab)")"
check "E3 ...including the unrelated line" "1" "$(grep -c important "$(tab)")"
case "$CRON_ERR" in *"was not modified"*) ok "E4 ...and says the crontab was not modified" ;;
  *) bad "E4 ...and says the crontab was not modified" "$CRON_ERR" ;; esac

# ---- F. a crontab(1) that lies is caught by reading back --------------------
#
# rc=0 is not evidence that what you asked for is what is installed. Every
# incident in this project's history that mattered was found by looking at the
# result rather than at the exit code.
seed '0 1 * * * important'
CRONTAB_MODE=liar
cron_block_install "$ME" zfs-backup-host "$(body 'new')"
rc=$?
CRONTAB_MODE=ok
# Here the crontab DID change, and the restore cannot be verified either --
# which is the one case that deserves the loud exit code and leaving the prior
# content on disk for a human.
check "F1 a write that stores something else is the LOUD failure" "2" "$rc"
case "$CRON_ERR" in *"reading it back gave something else"*) ok "F2 ...named exactly" ;;
  *) bad "F2 ...named exactly" "$CRON_ERR" ;; esac

# ---- G. read and diff -------------------------------------------------------
seed '# BEGIN zfs-backup-host' '1 * * * * a' '2 * * * * b' '# END zfs-backup-host' 'tail line'
check "G1 read returns the body without markers" "1 * * * * a|2 * * * * b" \
      "$(cron_block_read "$ME" zfs-backup-host | tr '\n' '|' | sed 's/|$//')"
check "G2 reading an absent block is empty and successful" "" \
      "$(cron_block_read "$ME" no-such-block; echo -n)"
cron_block_diff "$ME" zfs-backup-host "$(body '1 * * * * a' '2 * * * * b')" >/dev/null
check "G3 diff of an identical body reports no change" "0" "$?"
d=$(cron_block_diff "$ME" zfs-backup-host "$(body '9 * * * * c')"; echo "rc=$?")
case "$d" in *"+9 * * * * c"*) ok "G4 diff shows the incoming line" ;;
  *) bad "G4 diff shows the incoming line" "$d" ;; esac
check "G5 ...and diff changes nothing" "1" "$(grep -c '1 \* \* \* \* a' "$(tab)")"

# ---- H. the shape the existing hosts already have ---------------------------
#
# Adoption must work on the crontabs that exist TODAY, markers and all:
# metropolis pve1's root crontab is two loose lines followed by a
# zfs-backup-host block whose BEGIN carries a descriptive tail.
seed \
  '0 8 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log' \
  '15 * * * * /root/.zfs-snapshot-all-update-state/update-control.sh --self-update' \
  '# BEGIN zfs-backup-host (host-level jobs kept by zfs-backup.sh -- do not hand-edit)' \
  '0 7 * * * /root/scripts/alert-digest.sh 2>>/root/scripts/cron.log' \
  '# END zfs-backup-host'
cron_block_install "$ME" zfs-backup-host "$(body '0 7 * * * /root/scripts/alert-digest.sh 2>>/root/scripts/cron.log')"
check "H1 a real-world block is matched despite its descriptive BEGIN tail" "0" "$?"
check "H2 ...the tail is kept" "1" \
      "$(grep -c 'kept by zfs-backup.sh -- do not hand-edit' "$(tab)")"
check "H3 ...the loose lines are still there (adoption is a separate decision)" "2" \
      "$(grep -cE '^(0 8|15) ' "$(tab)")"

# ---- I. how a user is addressed --------------------------------------------
#
# Load-bearing, and I nearly changed it silently while unifying the writers: the
# refactor's first version addressed root with `crontab -u root`, which is more
# literal and made twelve zfsbackup assertions pass for the wrong reason -- the
# suites emulate root as an ordinary user through a stub that only knows `-l`,
# so the strict form read an empty crontab and every diff said "no change".
#
# Pinned here so the next person to find `cron_is_self` odd reads why before
#changing it.
check "I1 my own name is self" "0" "$(cron_is_self "$ME"; echo $?)"
check "I2 root counts as self (see the comment on cron_is_self)" "0"       "$(cron_is_self root; echo $?)"
check "I3 anyone else does not" "1" "$(cron_is_self somebodyelse; echo $?)"
# ...and the addressing actually reaches the stub in that form.
none
cron_block_install "$ME" zfs-backup-host "$(body '1 * * * * self')" >/dev/null
check "I4 a self write lands in this user's crontab" "1"       "$(grep -c 'self' "$TMPD/tabs/$ME")"
cron_block_install someotheruser zfs-backup-host "$(body '1 * * * * other')" >/dev/null
check "I5 another user's write goes to THEIR crontab, not mine" "1"       "$(grep -c 'other' "$TMPD/tabs/someotheruser" 2>/dev/null || echo 0)"
check "I6 ...and did not touch mine" "0"       "$(grep -c 'other' "$TMPD/tabs/$ME")"

# ---- J. ensure_line: the shape deploy.sh's four sites had ------------------
#
# "If the crontab already mentions this script leave it alone, else append" --
# but into a managed block, and moving any loose copy in instead of letting two
# schedules run side by side.
none
cron_block_ensure_line "$ME" zfs-backup-host '/root/scripts/check-pool-capacity.sh'     '0 8 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log' '(host)'
check "J1 into an empty crontab: rc" "0" "$?"
check "J1 ...the line is inside the block" "1"       "$(sed -n '/^# BEGIN zfs-backup-host/,/^# END zfs-backup-host/p' "$(tab)" | grep -c 'check-pool-capacity')"

# Idempotent: running deploy.sh twice must not double anything.
cron_block_ensure_line "$ME" zfs-backup-host '/root/scripts/check-pool-capacity.sh'     '0 8 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log'
check "J2 a second identical run changes nothing" "0" "$CRON_CHANGED"
check "J2 ...and there is still exactly one copy" "1" "$(grep -c 'check-pool-capacity' "$(tab)")"

# A second, different line joins the same block instead of replacing it.
cron_block_ensure_line "$ME" zfs-backup-host 'update-control.sh --self-update'     '15 * * * * /root/.zfs-snapshot-all-update-state/update-control.sh --self-update'
check "J3 a second line joins the block" "2"       "$(sed -n '/^# BEGIN zfs-backup-host/,/^# END zfs-backup-host/p' "$(tab)" | grep -cE '^[0-9*]')"

# Changing the line's content replaces it rather than adding a variant.
cron_block_ensure_line "$ME" zfs-backup-host '/root/scripts/check-pool-capacity.sh'     '0 9 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log'
check "J4 a changed schedule replaces, not duplicates" "1" "$(grep -c 'check-pool-capacity' "$(tab)")"
check "J4 ...with the new schedule" "1" "$(grep -c '^0 9 .*check-pool-capacity' "$(tab)")"

# ---- K. adoption: the loose line is MOVED, not left to run twice ------------
#
# This is the only part of the whole unification that touches something already
# running on a live host, so it is pinned from both directions: the loose copy
# goes, an identical managed copy exists, and nothing else moves.
seed   '# a human wrote this'   '0 8 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log'   '15 * * * * /root/.zfs-snapshot-all-update-state/update-control.sh --self-update'   '30 3 * * * /usr/local/bin/something-else'   '# BEGIN zfs-backup-managed (generated by gen-cron.sh)'   '1 * * * * snapsend'   '# END zfs-backup-managed'
cron_block_ensure_line "$ME" zfs-backup-host '/root/scripts/check-pool-capacity.sh'     '0 8 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log' '(host)'
check "K1 the loose copy is reported as adopted" "1" "$CRON_ADOPTED"
check "K2 ...and there is exactly one copy left" "1" "$(grep -c 'check-pool-capacity' "$(tab)")"
check "K3 ...inside the block" "1"       "$(sed -n '/^# BEGIN zfs-backup-host/,/^# END zfs-backup-host/p' "$(tab)" | grep -c 'check-pool-capacity')"
check "K4 the OTHER loose line is untouched" "1"       "$(grep -c 'update-control.sh --self-update' "$(tab)")"
check "K5 ...still outside any block" "0"       "$(sed -n '/^# BEGIN zfs-backup-host/,/^# END zfs-backup-host/p' "$(tab)" | grep -c 'update-control')"
check "K6 the human's line survives" "1" "$(grep -c 'something-else' "$(tab)")"
check "K7 the managed block survives" "1" "$(grep -c '^1 \* \* \* \* snapsend$' "$(tab)")"

# A line that merely LOOKS similar is not adopted: the match is the caller's own
# identifying substring, so adoption can never reach further than the detection
# deploy.sh already did before appending.
seed '0 8 * * * /usr/local/bin/my-own-capacity-check.sh'
cron_block_ensure_line "$ME" zfs-backup-host '/root/scripts/check-pool-capacity.sh'     '0 8 * * * /root/scripts/check-pool-capacity.sh'
check "K8 an unrelated line matching neither path stays put" "1"       "$(grep -c 'my-own-capacity-check' "$(tab)")"
check "K9 ...and is not inside the block" "0"       "$(sed -n '/^# BEGIN zfs-backup-host/,/^# END zfs-backup-host/p' "$(tab)" | grep -c 'my-own')"

# ---- L. older spellings of the same job are normalised, not stacked --------
#
# deploy.sh's updater line has had three shapes. Leaving an obsolete one next to
# the current one would run the update twice an hour, and the previous code did
# exactly that whenever a current-shaped line already existed alongside an old
# one (its own comment records the defect).
seed   '# a human wrote this'   '15 * * * * /root/scripts/zfs-snapshot-all/deploy.sh --self-update'   '15 * * * * cd /root/scripts/zfs-snapshot-all && git pull --ff-only origin main'   '30 3 * * * /usr/local/bin/keepme'
ALSO='/root/scripts/zfs-snapshot-all/deploy.sh --self-update
cd /root/scripts/zfs-snapshot-all && git pull --ff-only origin main'
cron_block_ensure_line "$ME" zfs-backup-host 'update-control.sh --self-update'     '15 * * * * /root/.zfs-snapshot-all-update-state/update-control.sh --self-update' '(host)' "$ALSO"
check "L1 both obsolete shapes are adopted away" "2" "$CRON_ADOPTED"
check "L2 ...leaving exactly one updater line" "1"       "$(grep -cE 'self-update|git pull --ff-only' "$(tab)")"
check "L3 ...the current one" "1" "$(grep -c 'update-control.sh --self-update' "$(tab)")"
check "L4 ...inside the block" "1"       "$(sed -n '/^# BEGIN zfs-backup-host/,/^# END zfs-backup-host/p' "$(tab)" | grep -c 'update-control')"
check "L5 the human's line is untouched" "1" "$(grep -c keepme "$(tab)")"

# ---- M. adopt keeps a hand-tuned line's text --------------------------------
#
# "already present, leaving it alone" is a promise deploy.sh makes today, and
# moving a line into the block must not quietly break it. An operator who
# changed 08:00 to 06:00 keeps 06:00; only the line's LOCATION changes.
seed '0 6 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log'
cron_block_adopt_line "$ME" zfs-backup-host '/root/scripts/check-pool-capacity.sh'     '0 8 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log' '(host)'
check "M1 the hand-tuned schedule survives adoption" "1" "$(grep -c '^0 6 ' "$(tab)")"
check "M2 ...and the default did NOT overwrite it" "0" "$(grep -c '^0 8 ' "$(tab)")"
check "M3 ...but it now lives in the block" "1"       "$(sed -n '/^# BEGIN zfs-backup-host/,/^# END zfs-backup-host/p' "$(tab)" | grep -c 'check-pool-capacity')"
check "M4 ...and only once" "1" "$(grep -c 'check-pool-capacity' "$(tab)")"

# With nothing to adopt, the default is what gets installed.
none
cron_block_adopt_line "$ME" zfs-backup-host '/root/scripts/check-pool-capacity.sh'     '0 8 * * * /root/scripts/check-pool-capacity.sh 2>>/root/scripts/cron.log' '(host)'
check "M5 with nothing present, the default is used" "1" "$(grep -c '^0 8 ' "$(tab)")"

echo "--------------------------------------------"
echo "PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
